package model;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * Customers generated by hbm2java
 */
@Entity
@Table(name = "customers", catalog = "vehicle_config")
public class Customers implements java.io.Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 4929691469488874394L;
	@Id
	@Column(name="id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer id;
	@Column(name = "cname", nullable = false, length = 20)
	private String cname;
	@Column(name = "caddr", nullable = false, length = 100)
	private String caddr;
	@Column(name = "email", nullable = false, length = 50)
	private String email;
	@Column(name = "telephone", nullable = false, length = 11)
		private String telephone;
	@Column(name = "fax", nullable = false, length = 11)
	private String fax;
	@Column(name = "holding", nullable = false, length = 10)
	private String holding;
	@Column(name = "authperson", nullable = false, length = 20)
		private String authperson;
	@Column(name = "designation", nullable = false, length = 10)
		private String designation;
	@Column(name = "gstno", nullable = false, length = 30)
	private String gstno;
	@Column(name = "panno", nullable = false, length = 30)
	private String panno;
	@Column(name = "username", nullable = false, length = 20)
	private String username;
	@Column(name = "password", nullable = false, length = 20)
		private String password;
	public Customers( String cname, String caddr, String email, String telephone, String fax, String holding,
			String authperson, String designation, String gstno, String panno, String username, String password) {
		super();
		
		this.cname = cname;
		this.caddr = caddr;
		this.email = email;
		this.telephone = telephone;
		this.fax = fax;
		this.holding = holding;
		this.authperson = authperson;
		this.designation = designation;
		this.gstno = gstno;
		this.panno = panno;
		this.username = username;
		this.password = password;
	}
	public Customers() {
		super();
		// TODO Auto-generated constructor stub
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getCname() {
		return cname;
	}
	public void setCname(String cname) {
		this.cname = cname;
	}
	public String getCaddr() {
		return caddr;
	}
	public void setCaddr(String caddr) {
		this.caddr = caddr;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getTelephone() {
		return telephone;
	}
	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}
	public String getFax() {
		return fax;
	}
	public void setFax(String fax) {
		this.fax = fax;
	}
	public String getHolding() {
		return holding;
	}
	public void setHolding(String holding) {
		this.holding = holding;
	}
	public String getAuthperson() {
		return authperson;
	}
	public void setAuthperson(String authperson) {
		this.authperson = authperson;
	}
	public String getDesignation() {
		return designation;
	}
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	public String getGstno() {
		return gstno;
	}
	public void setGstno(String gstno) {
		this.gstno = gstno;
	}
	public String getPanno() {
		return panno;
	}
	public void setPanno(String panno) {
		this.panno = panno;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}

}