package model;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * Models generated by hbm2java
 */
@Entity
@Table(name = "models", catalog = "vehicle_config")
public class Models implements java.io.Serializable{

	/**
	 *
	 */
	private static final long serialVersionUID = -1630789088569652062L;
	
	private Integer id;
	
	private String modelName;
	private String modelDescip;
	private String mfgDate;
	private BigDecimal price;

	private int manufacturer_id;
	private String model_img;
	

	private int mid;
	private int segment_id;
	private Set<Integer> altTbls = new HashSet<Integer>(0);
	private Set<ModelDetail> modelDetails = new HashSet<ModelDetail>(0);

	public Models() {
	}

	public Models(int manufacturer, int segments, String modelName, String modelDescip, 
			String mfgDate, BigDecimal price, int mid,String model_img) {
		this.manufacturer_id = manufacturer;
		this.segment_id = segments;
		this.modelName = modelName;
		this.modelDescip = modelDescip;
		this.mfgDate = mfgDate;
		this.price = price;
		this.mid=mid;
		this.model_img=model_img;
	}

	public Models(int manufacturer, int segments, String modelName, String modelDescip,
			String mfgDate, BigDecimal price, Set<Integer> altTbls, Set<ModelDetail> modelDetails, String model_img,int mid) {
		this.manufacturer_id = manufacturer;
		this.segment_id = segments;
		this.modelName = modelName;
		this.modelDescip = modelDescip;
		this.mfgDate = mfgDate;
		this.price = price;
		this.altTbls = altTbls;
		this.modelDetails = modelDetails;
		this.mid=mid;
		this.model_img=model_img;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name="manufacturer_id", nullable = false)
	public int getManufacturer_id() {
		return this.manufacturer_id;
	}

	public void setManufacturer_id(int manufacturer) {
		this.manufacturer_id = manufacturer;
	}

	@Column(name="segment_id", nullable = false)
	public int getSegment_id() {
		return this.segment_id;
	}

	public void setSegment_id(int segments) {
		this.segment_id = segments;
	}

	@Column(name = "model_name", nullable = false)
	public String getModelName() {
		return this.modelName;
	}

	public void setModelName(String modelName) {
		this.modelName = modelName;
	}

	@Column(name = "model_descip", nullable = false, length = 60)
	public String getModelDescip() {
		return this.modelDescip;
	}

	public void setModelDescip(String modelDescip) {
		this.modelDescip = modelDescip;
	}

	@Column(name = "mfg_date", nullable = false, length = 10)
	public String getMfgDate() {
		return this.mfgDate;
	}

	public void setMfgDate(String mfgDate) {
		this.mfgDate = mfgDate;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Transient
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "models")
	public Set<Integer> getAltTbls() {
		return this.altTbls;
	}

	public void setAltTbls(Set<Integer> altTbls) {
		this.altTbls = altTbls;
	}

	@Transient
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	@JoinColumn(name = "model_id", referencedColumnName="model_id")
	public Set<ModelDetail> getModelDetails() {
		return this.modelDetails;
	}

	public void setModelDetails(Set<ModelDetail> modelDetails) {
		this.modelDetails = modelDetails;
	}
	
	@Column(name="mid", nullable=false)
	public int getMid() {
		return mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}
	@Column(name="model_img" ,nullable=false)
	public String getModel_img() {
		return model_img;
	}

	public void setModel_img(String model_img) {
		this.model_img = model_img;
	}

}
